---
groups:
    - name: all
      jobs:
        - build
        # - publish-to-artifactory
resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
  - name: repo-develop
    type: git
    source:
      uri: git@github.com:bijukunjummen/sample-spring-cloud-svc-ci.git
      private_key: {{github-private-key}}
      branch: develop

  - name: repo-pipeline
    type: git
    source:
      uri: git@github.com:bijukunjummen/sample-with-artifactory-resource.git
      private_key: {{github-private-key}}
      branch: master

  - name: file-repository
    type: artifactory
    source:
      endpoint: http://192.168.99.100:8081/artifactory
      repository: "/ext-release-local"
      regex: "sample-spring-cloud-svc-ci-(?<version>.*).jar"
      username: admin
      password: password
      skip_ssl_verification: true      

jobs:
  - name: build
    serial: true
    public: true
    plan:
      - aggregate:
        - get: repo
          resource: repo-develop
        - get: pipeline
          resource: repo-pipeline
          # trigger: true
      - task: compile
        file: pipeline/tasks/build.yml

      - put: file-repository
        params:
          file: "./build/sample-spring-cloud-svc-ci-*.jar"