---
groups:
    - name: all
      jobs:
        - build
        # - publish-to-artifactory

resources:
  - name: repo-develop
    type: git
    source:
      uri: git@github.com:bijukunjummen/sample-spring-cloud-svc-ci.git
      private_key: {{github-private-key}}
      branch: develop

  - name: repo-pipeline
    type: git
    source:
      uri: git@github.com:bijukunjummen/sample-with-artifactory-resource.git
      private_key: {{github-private-key}}
      branch: master

jobs:
  - name: build
    serial: true
    public: true
    plan:
      - aggregate:
        - get: repo
          resource: repo-develop
        - get: pipeline
          resource: repo-pipeline
          # trigger: true
      - task: compile
        file: pipeline/tasks/build.yml