---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8-alpine'

inputs:
  - name: repo
outputs:
  - name: build
run:
  path: /bin/sh
  args: 
    - -c
    - |
        cd repo
        ./gradlew clean build
params:
  JAVA_OPTIONS: 
