---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
    # tag: '8-alpine'

inputs:
  - name: repo
  - name: pipeline
outputs:
  - name: build
run:
  path: /bin/bash
  args: ["-c", "pipeline/tasks/scripts/build.sh"]
params:
  JAVA_OPTIONS: 
